name: "CI Builds"
on: push
  branches:
    - master
jobs:
  build-linux:
    strategy:
      matrix:
        dist:
          - ubuntu.24.04
    runs-on: ubuntu-latest
    container: veyon/ci.linux.${{matrix.dist}}
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: true
      - run: .ci/linux.${{matrix.dist}}/script.sh $GITHUB_WORKSPACE /tmp
